// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp8IODWsQYk7WCt99XPxVoYf6aJ4Uw8bg',
    appId: '1:808485784600:web:322cea427edeada45e476d',
    messagingSenderId: '808485784600',
    projectId: 'abp-pgl',
    authDomain: 'abp-pgl.firebaseapp.com',
    storageBucket: 'abp-pgl.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVRdNgqmFv2FijwCjeg0dWhuUMYtoLhPs',
    appId: '1:808485784600:android:f1d3e5a348491a495e476d',
    messagingSenderId: '808485784600',
    projectId: 'abp-pgl',
    storageBucket: 'abp-pgl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-jdc8EFbfpg2v4AVRaPWm28ONVh1bFcw',
    appId: '1:808485784600:ios:9d27416439448cc65e476d',
    messagingSenderId: '808485784600',
    projectId: 'abp-pgl',
    storageBucket: 'abp-pgl.firebasestorage.app',
    iosBundleId: 'com.example.pglUt3proyecto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-jdc8EFbfpg2v4AVRaPWm28ONVh1bFcw',
    appId: '1:808485784600:ios:9d27416439448cc65e476d',
    messagingSenderId: '808485784600',
    projectId: 'abp-pgl',
    storageBucket: 'abp-pgl.firebasestorage.app',
    iosBundleId: 'com.example.pglUt3proyecto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp8IODWsQYk7WCt99XPxVoYf6aJ4Uw8bg',
    appId: '1:808485784600:web:b2d6d2a8a17b9fc55e476d',
    messagingSenderId: '808485784600',
    projectId: 'abp-pgl',
    authDomain: 'abp-pgl.firebaseapp.com',
    storageBucket: 'abp-pgl.firebasestorage.app',
  );
}
